import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,ShieldCheck,Clock,Globe2,ArrowUpRight,ChevronDown,BookOpen,Radio,Languages,X,CheckCircle2}from'lucide-react';import'./styles.css';

const articles=[
{id:1,tier:1,source:'OFFICIAL',country:'잉글랜드',league:'프리미어리그',time:'12분 전',title:'Manchester City complete signing of teenage midfielder',ko:'맨체스터 시티, 유망주 미드필더 영입 공식 발표',summary:'구단은 장기 계약 체결을 공식 확인했다. 선수는 프리시즌부터 1군에 합류하며 세부 이적료는 공개되지 않았다.',tags:['이적','공식'],confidence:99,color:'#65d89a',url:'https://www.mancity.com/news'},
{id:2,tier:1,source:'The Athletic',country:'잉글랜드',league:'프리미어리그',time:'28분 전',title:'Arsenal make contact over deal for versatile defender',ko:'아스널, 멀티 수비수 영입 위해 첫 접촉',summary:'아스널이 선수 측과 초기 대화를 시작했다. 아직 공식 제안은 없지만 구단 내부에서 최우선 후보로 평가한다.',tags:['프리미어리그','이적'],confidence:92,color:'#5be0d0',url:'https://www.nytimes.com/athletic/football/'},
{id:3,tier:1,source:'Fabrizio Romano',country:'이탈리아',league:'세리에 A',time:'41분 전',title:'Agreement reached, final documents being prepared',ko:'협상 합의 도달…최종 서류 준비 중',summary:'구단과 선수 모두 계약 조건에 동의했다. 메디컬 테스트 일정이 조율 중이며 서명만 남은 단계로 전해진다.',tags:['Here we go','속보'],confidence:90,color:'#5be0d0',url:'https://x.com/FabrizioRomano'},
{id:4,tier:3,source:'Sky Sports',country:'잉글랜드',league:'프리미어리그',time:'1시간 전',title:'United remain interested as talks continue this week',ko:'맨유 관심 여전…이번 주 협상 계속',summary:'양 구단 간 가치 평가 차이가 있지만 대화는 중단되지 않았다. 대체 후보도 동시에 검토 중이다.',tags:['맨유','협상'],confidence:78,color:'#f0c96b',url:'https://www.skysports.com/football/news'},
{id:5,tier:3,source:'RMC Sport',country:'프랑스',league:'리그 1',time:'2시간 전',title:'PSG considering fresh approach for Serie A star',ko:'PSG, 세리에A 스타에 새 제안 검토',summary:'PSG가 공격진 개편 과정에서 새로운 제안을 논의하고 있다. 선수의 현 소속팀은 잔류를 우선한다.',tags:['리그1','루머'],confidence:73,color:'#f0c96b',url:'https://www.rmcsport.bfmtv.com/football/'},
{id:6,tier:4,source:'AS',country:'스페인',league:'라리가',time:'3시간 전',title:'Madrid could enter race if asking price drops',ko:'요구액 낮아지면 레알 마드리드 영입전 합류 가능',summary:'현지 매체는 조건부 관심을 보도했다. 구체적인 협상이나 접촉 정황은 확인되지 않아 추가 검증이 필요하다.',tags:['라리가','관심'],confidence:55,color:'#ff9e71',url:'https://as.com/futbol/'},
{id:7,tier:6,source:'Football Insider',country:'잉글랜드',league:'프리미어리그',time:'4시간 전',title:'Exclusive: shock swap deal discussed behind scenes',ko:'독점: 깜짝 스왑딜 물밑 논의',summary:'익명 관계자를 인용한 주장이다. 다른 주요 매체의 교차 보도가 없고 거래 구조도 불분명하다.',tags:['독점','주의'],confidence:31,color:'#ff6d7a',url:'https://www.footballinsider247.com/'}];
const tierMeta={1:{rank:'챌린저',icon:'◆',name:'공식급 신뢰',desc:'공식 발표 · 최고 신뢰 기자',c:'#f3c969'},2:{rank:'다이아몬드',icon:'◇',name:'최상위 신뢰',desc:'세계적 특종 기자 · 확정 단계',c:'#69d9e8'},3:{rank:'플래티넘',icon:'⬙',name:'높은 신뢰',desc:'주요 방송사 · 검증된 매체',c:'#79e2ca'},4:{rank:'골드',icon:'⬟',name:'보통 신뢰',desc:'유력 현지 매체 · 추가 확인 필요',c:'#f0b93f'},5:{rank:'실버',icon:'⬡',name:'주의 필요',desc:'단일 출처 · 근거가 제한된 보도',c:'#b9c4ca'},6:{rank:'브론즈',icon:'⬢',name:'낮은 신뢰',desc:'단독 루머 · 교차검증 없음',c:'#b97850'}};
const countries=['전체','잉글랜드','스페인','이탈리아','프랑스'];
const leagues=['전체','프리미어리그','라리가','세리에 A','리그 1'];
const leaguesByCountry={잉글랜드:['프리미어리그'],스페인:['라리가'],이탈리아:['세리에 A'],프랑스:['리그 1']};
// 매년 반복되는 일반적인 이적시장 운영 기간. 운영 시 리그 공식 일정 API로 교체할 수 있습니다.
const transferWindows={잉글랜드:[[1,1,2,3],[6,1,9,1]],스페인:[[1,2,2,3],[7,1,9,1]],이탈리아:[[1,2,2,3],[7,1,9,1]],프랑스:[[1,1,2,3],[6,10,9,1]]};
const inWindow=(name,now=new Date())=>(transferWindows[name]||[]).some(([sm,sd,em,ed])=>{const y=now.getFullYear(),start=new Date(y,sm-1,sd),end=new Date(y,em-1,ed,23,59,59);return now>=start&&now<=end});
const scheduleFor=(selectedCountry,now=new Date())=>{const active=selectedCountry==='전체'?countries.slice(1).filter(c=>inWindow(c,now)):inWindow(selectedCountry,now)?[selectedCountry]:[];return{active,interval:active.length?5*60*1000:60*60*1000}};
function App(){const[tier,setTier]=useState(0),[country,setCountry]=useState('전체'),[league,setLeague]=useState('전체'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[lang,setLang]=useState('KO'),[lastUpdated,setLastUpdated]=useState(new Date()),[refreshing,setRefreshing]=useState(false);const visibleLeagues=country==='전체'?leagues:['전체',...(leaguesByCountry[country]||[])];const refresh=async()=>{setRefreshing(true);try{const response=await fetch('/api/articles',{cache:'no-store'});if(response.ok){/* 실제 API 연결 시 기사 상태를 여기서 갱신 */}}catch{}finally{setLastUpdated(new Date());setRefreshing(false)}};useEffect(()=>{const{interval}=scheduleFor(country);const timer=setInterval(refresh,interval);return()=>clearInterval(timer)},[country]);const schedule=scheduleFor(country);const filtered=useMemo(()=>articles.filter(a=>(!tier||a.tier===tier)&&(country==='전체'||a.country===country)&&(league==='전체'||a.league===league)&&(`${a.title} ${a.ko} ${a.source} ${a.country} ${a.league}`.toLowerCase().includes(query.toLowerCase()))),[tier,country,league,query]);return <div className="app"><header><div className="brand"><div className="logo"><ShieldCheck/></div><b>풋볼 <i>티어</i></b></div><nav><a className="active">뉴스 피드</a><a>신뢰도 가이드</a><a>소스 랭킹</a></nav><button className="lang" onClick={()=>setLang(lang==='KO'?'EN':'KO')}><Globe2 size={16}/>{lang}<ChevronDown size={14}/></button></header>
<main><section className="hero"><div className="eyebrow"><Radio size={14}/> LIVE INTELLIGENCE</div><h1>소문은 걷어내고,<br/><span>사실만 읽으세요.</span></h1><p>전 세계 축구 뉴스를 신뢰도별로 분류하고<br/>원문 번역과 핵심 요약을 한눈에 제공합니다.</p><div className="stats"><div><strong>37</strong><small>오늘 수집된 기사</small></div><div><strong>12</strong><small>검증된 소스</small></div><div><strong>6</strong><small>지원 언어</small></div></div></section>
<section className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="팀, 선수, 리그 또는 매체 검색"/></div><div className="updatePanel"><div className="update"><span className={refreshing?'refreshing':''}/>{refreshing?'기사 업데이트 중':`마지막 업데이트 ${lastUpdated.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`}</div><button onClick={refresh} disabled={refreshing}>지금 새로고침</button><small>{schedule.active.length?`이적시장 모드 · 5분 간격 (${schedule.active.join(' · ')})`:'일반 모드 · 1시간 간격'}</small></div></section>
<section className="categoryFilters"><div className="filterGroup"><b>국가별</b>{countries.map(c=><button key={c} className={country===c?'on':''} onClick={()=>{setCountry(c);setLeague('전체')}}>{c}</button>)}</div><div className="filterGroup"><b>리그별</b>{visibleLeagues.map(l=><button key={l} className={league===l?'on':''} onClick={()=>setLeague(l)}>{l}</button>)}</div></section><section className="filters"><button className={!tier?'on':''} onClick={()=>setTier(0)}>전체 신뢰도 <em>{articles.length}</em></button>{Object.entries(tierMeta).map(([k,v])=><button key={k} className={tier==k?'on':''} onClick={()=>setTier(+k)}><i style={{background:v.c}}/>{v.icon} {v.rank} <em>{articles.filter(a=>a.tier==k).length}</em></button>)}</section>
<div className="layout"><section className="feed"><div className="section-title"><div><span>THE DAILY FEED</span><h2>{league!=='전체'?league:country!=='전체'?country:'주요'} 축구 뉴스</h2></div><button>최신순 <ChevronDown size={14}/></button></div>{filtered.map(a=><article key={a.id} onClick={()=>setSelected(a)}><div className="tierbar" style={{background:a.color}}/><div className="cardtop"><span className={`tier rank-${a.tier}`} style={{color:tierMeta[a.tier].c}}>{tierMeta[a.tier].icon} {tierMeta[a.tier].rank}</span><span className="source">{a.source}</span><span className="country">{a.country}</span><span className="country leagueBadge">{a.league}</span><span className="time"><Clock size={13}/>{a.time}</span></div><h3>{a.ko}</h3><p className="original">{a.title}</p><p className="summary">{a.summary}</p><footer><div>{a.tags.map(t=><span key={t}>#{t}</span>)}</div><button>번역 · 요약 보기 <ArrowUpRight size={15}/></button></footer></article>)}{!filtered.length&&<div className="empty">검색 결과가 없습니다.</div>}</section>
<aside><div className="guide"><span className="label">TRUST RANK SYSTEM</span><h3>기사의 랭크는 어떻게<br/>판정하나요?</h3><p>출처의 과거 적중률, 취재 접근성, 교차 검증 여부를 종합합니다.</p>{Object.entries(tierMeta).map(([k,v])=><div className="guideRow" key={k}><b className="rankIcon" style={{color:v.c}}>{v.icon}</b><div><strong>{v.rank} · {v.name}</strong><small>{v.desc}</small></div></div>)}<button><BookOpen size={16}/>평가 기준 자세히 보기</button></div><div className="sourceRank"><span className="label">TOP SOURCES</span><h3>이번 주 소스 랭킹</h3>{['구단 공식 채널','David Ornstein','Fabrizio Romano','BBC Sport'].map((x,i)=><div><b>{i+1}</b><span>{x}<small>{i?'전문 기자':'공식 발표'}</small></span><em>{99-i*3}</em></div>)}</div></aside></div></main>
<footer className="sitefoot"><b>풋볼티어 · FOOTBALL TIER</b><span>축구 뉴스를 더 정확하고, 더 빠르게.</span><small>신뢰도 점수는 참고 지표이며 사실을 보증하지 않습니다.</small></footer>
{selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className={`modalTier rank-${selected.tier}`} style={{color:tierMeta[selected.tier].c}}>{tierMeta[selected.tier].icon} {tierMeta[selected.tier].rank} · 신뢰도 {selected.confidence}</div><h2>{selected.ko}</h2><p className="modalOriginal">{selected.title}</p><div className="translation"><Languages/><div><b>AI 번역</b><p>{selected.ko}. {selected.summary}</p></div></div><div className="bullets"><b>3줄 핵심 요약</b><p><CheckCircle2/> {selected.summary}</p><p><CheckCircle2/> 보도 출처는 {selected.source}이며 {tierMeta[selected.tier].rank} 랭크, 신뢰도 {selected.confidence}점입니다.</p><p><CheckCircle2/> 공식 발표 전까지 상황이 바뀔 수 있습니다.</p></div><a className="originalBtn" href={selected.url} target="_blank" rel="noopener noreferrer">원문 기사로 이동 <ArrowUpRight/></a></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);

