import React,{useCallback,useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,Clock,Globe2,ArrowUpRight,ChevronDown,Radio,Languages,X,CheckCircle2,CalendarDays,ChevronLeft,ChevronRight,PlayCircle,ExternalLink}from'lucide-react';
import'./styles.css';

const fallbackArticles=[
{id:1,tier:1,source:'OFFICIAL',country:'잉글랜드',league:'프리미어리그',time:'샘플',publishedAt:new Date().toISOString(),title:'Manchester City complete signing of teenage midfielder',ko:'맨체스터 시티, 유망주 미드필더 영입 공식 발표',summary:'구단은 장기 계약 체결을 공식 확인했다.',tags:['이적','공식'],confidence:99,color:'#65d89a',url:'https://www.mancity.com/news'},
{id:2,tier:2,source:'The Athletic',country:'잉글랜드',league:'프리미어리그',time:'샘플',publishedAt:new Date().toISOString(),title:'Arsenal make contact over deal for versatile defender',ko:'아스널, 멀티 수비수 영입 위해 첫 접촉',summary:'아스널이 선수 측과 초기 대화를 시작했다.',tags:['프리미어리그','이적'],confidence:92,color:'#69d9e8',url:'https://www.nytimes.com/athletic/football/'},
{id:3,tier:2,source:'Fabrizio Romano',country:'이탈리아',league:'세리에 A',time:'샘플',publishedAt:new Date().toISOString(),title:'Agreement reached, final documents being prepared',ko:'협상 합의 도달…최종 서류 준비 중',summary:'구단과 선수 모두 계약 조건에 동의했다.',tags:['Here we go','속보'],confidence:90,color:'#69d9e8',url:'https://x.com/FabrizioRomano'}
];
const tierMeta={1:{rank:'공식·최상',icon:'◆',name:'최고 신뢰',c:'#f3c969'},2:{rank:'신뢰',icon:'◇',name:'높은 신뢰',c:'#69d9e8'},3:{rank:'참고',icon:'⬟',name:'추가 확인',c:'#f0b93f'},4:{rank:'주의',icon:'⬢',name:'낮은 신뢰',c:'#b97850'}};
const journalistRanking=[['David Ornstein','공식·최상'],['Paul Joyce','공식·최상'],['Simon Stone','공식·최상'],['James Pearce','공식·최상'],['Romeo Agresti','공식·최상'],['Fabrizio Romano','신뢰'],['Matteo Moretto','신뢰'],['Fabrice Hawkins','신뢰'],['Gianluca Di Marzio','신뢰'],['Florian Plettenberg','신뢰'],['Gerard Romero','신뢰'],['Ben Jacobs','신뢰'],['Tancredi Palmeri','주의']];
const siteRanking=[['구단 공식 채널','공식·최상'],['BBC Sport','신뢰'],['The Athletic','신뢰'],['The Times','신뢰'],['Sky Sports','신뢰'],['The Guardian','신뢰'],['The Telegraph','신뢰'],['Marca / L’Équipe','참고'],['ESPN / Goal','참고'],['90min / CaughtOffside','참고'],['The Sun / Tuttosport','주의']];
const videoCountries=['전체','대한민국','잉글랜드','스페인','이탈리아','프랑스'];
const footballVideos=[
 {country:'대한민국',channel:'박종윤(축구)',title:'안녕하세요. 박종윤입니다',description:'박종윤이 직접 전하는 축구 이야기와 채널 소개 영상입니다.',url:'https://www.youtube.com/watch?v=0JaJANnH8r0',thumb:'https://i.ytimg.com/vi/0JaJANnH8r0/hqdefault.jpg'},
 {country:'대한민국',channel:'달수네라이브',title:'박문성과 함께하는 대한민국 축구 분석',description:'박문성과 패널들이 대한민국 대표팀의 경기 내용과 주요 축구 이슈를 분석합니다.',url:'https://www.youtube.com/watch?v=8RC6Fk4hQ-s',thumb:'https://i.ytimg.com/vi/8RC6Fk4hQ-s/hqdefault.jpg'},
 {country:'대한민국',channel:'김진짜 Real KIM',title:'극적인 역전승이 가능했던 이유',description:'대한민국 대표팀 경기의 전술과 주요 장면을 알기 쉽게 분석합니다.',url:'https://www.youtube.com/watch?v=Ce93hCAcKMo',thumb:'https://i.ytimg.com/vi/Ce93hCAcKMo/hqdefault.jpg'},
 {country:'잉글랜드',channel:'Sky Sports News',title:'프리미어리그 최신 이적시장 소식',description:'아스널, 맨체스터 유나이티드, 뉴캐슬 등 프리미어리그 구단들의 이적 상황을 정리합니다.',url:'https://www.youtube.com/watch?v=uYFCjcioPBI',thumb:'https://i.ytimg.com/vi/uYFCjcioPBI/hqdefault.jpg'},
 {country:'잉글랜드',channel:'BBC Sport',title:'주말 축구 분석과 주요 이슈',description:'BBC 패널이 주말 경기 결과와 잉글랜드 축구의 주요 이슈를 분석합니다.',url:'https://www.youtube.com/watch?v=v6VvL2U09Zk',thumb:'https://i.ytimg.com/vi/v6VvL2U09Zk/hqdefault.jpg'},
 {country:'잉글랜드',channel:'Sky Sports Premier League',title:'맨체스터 유나이티드 이적 토크',description:'맨유의 선수단 구성과 이적시장 움직임을 다루는 축구 토크 영상입니다.',url:'https://www.youtube.com/watch?v=99sdQA6qHJo',thumb:'https://i.ytimg.com/vi/99sdQA6qHJo/hqdefault.jpg'},
 {country:'스페인',channel:'ESPN FC',title:'라리가 최신 이적 소식과 분석',description:'라리가와 프리미어리그의 주요 이적설을 패널들이 분석합니다.',url:'https://www.youtube.com/watch?v=CWRDGADhCTc',thumb:'https://i.ytimg.com/vi/CWRDGADhCTc/hqdefault.jpg'},
 {country:'스페인',channel:'Real Madrid',title:'레알 마드리드 라리가 경기 하이라이트',description:'레알 마드리드 공식 채널이 제공하는 라리가 경기 주요 장면입니다.',url:'https://www.youtube.com/watch?v=y-J_ZKFyWX8',thumb:'https://i.ytimg.com/vi/y-J_ZKFyWX8/hqdefault.jpg'},
 {country:'이탈리아',channel:'Serie A',title:'세리에 A 시즌 최고의 골',description:'세리에 A 공식 채널이 선정한 시즌 최고의 득점 장면을 모았습니다.',url:'https://www.youtube.com/watch?v=OFNqjj4_OVk',thumb:'https://i.ytimg.com/vi/OFNqjj4_OVk/hqdefault.jpg'},
 {country:'이탈리아',channel:'Serie A',title:'세리에 A 라운드 골 모음',description:'세리에 A 공식 채널에서 제공하는 라운드별 모든 득점 장면입니다.',url:'https://www.youtube.com/watch?v=i4OENgNSKXQ',thumb:'https://i.ytimg.com/vi/i4OENgNSKXQ/hqdefault.jpg'},
 {country:'이탈리아',channel:'IFTV',title:'세리에 A 우승 경쟁 분석',description:'이탈리아 축구 전문 채널이 세리에 A 선두 경쟁과 주요 구단을 분석합니다.',url:'https://www.youtube.com/watch?v=dPovQChQaGY',thumb:'https://i.ytimg.com/vi/dPovQChQaGY/hqdefault.jpg'},
 {country:'프랑스',channel:'Ligue 1 McDonald’s',title:'리그 1 라운드 종합 하이라이트',description:'리그 1 공식 채널에서 제공하는 주요 경기와 득점 장면 요약입니다.',url:'https://www.youtube.com/watch?v=GeBbIACa3AM',thumb:'https://i.ytimg.com/vi/GeBbIACa3AM/hqdefault.jpg'},
 {country:'프랑스',channel:'Ligue 1 McDonald’s',title:'리그 1 경기 주요 장면',description:'프랑스 리그 1 공식 채널의 라운드별 종합 영상입니다.',url:'https://www.youtube.com/watch?v=BBJWwQsUqus',thumb:'https://i.ytimg.com/vi/BBJWwQsUqus/hqdefault.jpg'},
 {country:'프랑스',channel:'Pierrot Le Foot',title:'리그 1 최신 경기 분석',description:'마르세유와 랑스 등 프랑스 주요 구단의 경기 흐름을 분석합니다.',url:'https://www.youtube.com/watch?v=5zqIYpwOZGE',thumb:'https://i.ytimg.com/vi/5zqIYpwOZGE/hqdefault.jpg'}
];
const countries=['전체','잉글랜드','스페인','이탈리아','프랑스'];
const leagues=['전체','프리미어리그','라리가','세리에 A','리그 1'];
const leaguesByCountry={잉글랜드:['프리미어리그'],스페인:['라리가'],이탈리아:['세리에 A'],프랑스:['리그 1']};
const teamsByLeague={'프리미어리그':['Arsenal','Aston Villa','Chelsea','Liverpool','Manchester City','Manchester United','Newcastle United','Tottenham Hotspur'],'라리가':['Athletic Bilbao','Atletico Madrid','Barcelona','Real Betis','Real Madrid','Real Sociedad','Sevilla','Villarreal'],'세리에 A':['AC Milan','Atalanta','Inter Milan','Juventus','Lazio','Napoli','Roma'],'리그 1':['Lille','Lyon','Marseille','Monaco','Nice','Paris Saint-Germain']};
const transferWindows={잉글랜드:[[1,1,2,3],[6,1,9,1]],스페인:[[1,2,2,3],[7,1,9,1]],이탈리아:[[1,2,2,3],[7,1,9,1]],프랑스:[[1,1,2,3],[6,10,9,1]]};
const inWindow=(name,now=new Date())=>(transferWindows[name]||[]).some(([sm,sd,em,ed])=>{const y=now.getFullYear(),start=new Date(y,sm-1,sd),end=new Date(y,em-1,ed,23,59,59);return now>=start&&now<=end});
const scheduleFor=(selectedCountry,now=new Date())=>{const active=selectedCountry==='전체'?countries.slice(1).filter(c=>inWindow(c,now)):inWindow(selectedCountry,now)?[selectedCountry]:[];return{active,interval:active.length?5*60*1000:60*60*1000}};
const isoDate=d=>d.toISOString().slice(0,10);
const today=()=>isoDate(new Date());
const daysAgo=n=>{const d=new Date();d.setDate(d.getDate()-n);return isoDate(d)};
const rangeDays=(from,to)=>Math.floor((new Date(`${to}T00:00:00`)-new Date(`${from}T00:00:00`))/86400000)+1;
const dateLabel=value=>new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'short',day:'numeric'}).format(new Date(value));

function App(){
 const[tier,setTier]=useState(0),[country,setCountry]=useState('전체'),[league,setLeague]=useState('전체'),[team,setTeam]=useState('전체'),[query,setQuery]=useState(''),[appliedQuery,setAppliedQuery]=useState(''),[selected,setSelected]=useState(null),[lang,setLang]=useState('KO'),[view,setView]=useState('news'),[rankTab,setRankTab]=useState('journalists'),[videoCountry,setVideoCountry]=useState('전체'),[detailOpen,setDetailOpen]=useState(false),[detailApplied,setDetailApplied]=useState(false);
 const[from,setFrom]=useState(daysAgo(6)),[to,setTo]=useState(today()),[page,setPage]=useState(1),[pageSize]=useState(10),[articles,setArticles]=useState([]),[total,setTotal]=useState(0),[tierCounts,setTierCounts]=useState({1:0,2:0,3:0,4:0}),[lastUpdated,setLastUpdated]=useState(new Date()),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const visibleLeagues=country==='전체'?leagues:['전체',...(leaguesByCountry[country]||[])];
 const loadArticles=useCallback(async()=>{if(detailApplied&&rangeDays(from,to)>31){setLoading(false);setError('기사량이 너무 많습니다. 날짜 범위는 최대 31일까지 선택할 수 있습니다.');return}setLoading(true);setError('');try{const p=new URLSearchParams({from:detailApplied?from:daysAgo(6),to:detailApplied?to:today(),page:String(page),pageSize:String(pageSize),country:detailApplied?country:'전체',league:detailApplied?league:'전체',team:detailApplied?team:'전체',tier:String(tier)});if(appliedQuery)p.set('q',appliedQuery);const response=await fetch(`/api/articles?${p}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'기사 조회에 실패했습니다.');setArticles(data.articles||[]);setTotal(data.totalResults||0);setTierCounts(data.tierCounts||{1:0,2:0,3:0,4:0});setLastUpdated(new Date());setLoading(false)}catch(e){setError(e.message);setArticles(fallbackArticles);setTotal(fallbackArticles.length);setTierCounts(fallbackArticles.reduce((acc,a)=>(acc[a.tier]=(acc[a.tier]||0)+1,acc),{1:0,2:0,3:0,4:0}));setLoading(false)}},[from,to,page,pageSize,country,league,team,tier,appliedQuery,detailApplied]);
 useEffect(()=>{loadArticles()},[loadArticles]);
 useEffect(()=>{const{interval}=scheduleFor(country);const timer=setInterval(loadArticles,interval);return()=>clearInterval(timer)},[country,loadArticles]);
 const schedule=scheduleFor(country);
 const filtered=articles;
 const totalPages=Math.max(1,Math.ceil(total/pageSize));
 const maxPage=Math.min(totalPages,100);
 const pageNumbers=useMemo(()=>{const start=Math.max(1,Math.min(page-2,maxPage-4)),end=Math.min(maxPage,start+4);return Array.from({length:end-start+1},(_,i)=>start+i)},[page,maxPage]);
 const goToPage=next=>{setPage(next);requestAnimationFrame(()=>document.querySelector('.feed')?.scrollIntoView({behavior:'smooth',block:'start'}))};
 const selectTier=nextTier=>{setPage(1);setTier(nextTier);requestAnimationFrame(()=>document.querySelector('.feed')?.scrollIntoView({behavior:'smooth',block:'start'}))};
 const applySearch=e=>{e.preventDefault();setPage(1);setAppliedQuery(query.trim())};
 const setPreset=days=>{const end=new Date(),start=new Date();start.setDate(start.getDate()-(days-1));setFrom(isoDate(start));setTo(isoDate(end));setPage(1)};
 const changeFrom=value=>{setFrom(value);setPage(1);if(rangeDays(value,to)>31)setError('기사량이 너무 많습니다. 시작일과 종료일을 31일 이내로 지정해 주세요.');else setError('')};
 const changeTo=value=>{setTo(value);setPage(1);if(rangeDays(from,value)>31)setError('기사량이 너무 많습니다. 시작일과 종료일을 31일 이내로 지정해 주세요.');else setError('')};
 const applyDetails=()=>{if(rangeDays(from,to)>31)return setError('기사량이 너무 많습니다. 시작일과 종료일을 31일 이내로 지정해 주세요.');setDetailApplied(true);setPage(1);setDetailOpen(false)};
 const resetDetails=()=>{setCountry('전체');setLeague('전체');setTeam('전체');setFrom(daysAgo(6));setTo(today());setDetailApplied(false);setPage(1);setDetailOpen(false)};
 return <div className="app"><header><div className="brand"><div className="logo"><img src="/football-tier-logo-transparent.png" alt="풋볼티어 로고"/></div><b>풋볼 <i>티어</i></b></div><nav><button className={view==='news'?'active':''} onClick={()=>setView('news')}>뉴스 피드</button><button className={view==='ranking'?'active':''} onClick={()=>setView('ranking')}>소스 랭킹</button><button className={view==='videos'?'active':''} onClick={()=>setView('videos')}>영상</button></nav><button className="lang" onClick={()=>setLang(lang==='KO'?'EN':'KO')}><Globe2 size={16}/>{lang}<ChevronDown size={14}/></button></header>
 <main>{view==='news'?<><section className="hero"><div className="eyebrow"><Radio size={14}/> FOOTBALL NEWS ARCHIVE</div><h1>루머에 흔들리지 마세요.<br/><span>진짜 축구 뉴스만, 티어로 확인하세요.</span></h1><p>이적설부터 공식 발표까지 전 세계 축구 소식을 한곳에서.<br/>출처 신뢰도와 핵심 요약으로 가장 중요한 순간을 누구보다 먼저 만나보세요.</p><div className="stats"><div><strong>{total.toLocaleString()}</strong><small>검색된 기사</small></div><div><strong>31D</strong><small>최대 조회 범위</small></div></div></section>
 <section className="toolbar"><form className="search" onSubmit={applySearch}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="팀, 선수, 리그 또는 매체 검색"/><button type="submit">검색</button><button type="button" className={`detailSearchBtn ${detailOpen?'on':''}`} onClick={()=>setDetailOpen(open=>!open)}>상세 검색 <ChevronDown size={13}/></button></form><div className="updatePanel"><div className="update"><span className={loading?'refreshing':''}/>{loading?'기사 불러오는 중':`마지막 업데이트 ${lastUpdated.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`}</div><button onClick={loadArticles} disabled={loading}>지금 새로고침</button><small>{schedule.active.length?`이적시장 모드 · 5분 간격 (${schedule.active.join(' · ')})`:'일반 모드 · 1시간 간격'}</small></div></section>
 {detailOpen&&<section className="gameSearchPanel"><div className="gameSearchHead"><CalendarDays/><div><b>뉴스 검색 조건</b></div></div><div className="gameSearchGrid"><label><span>조회 기간</span><div className="rangeField"><input type="date" max={to} value={from} onChange={e=>changeFrom(e.target.value)}/><em>—</em><input type="date" min={from} max={today()} value={to} onChange={e=>changeTo(e.target.value)}/></div><div className="quickRange"><button onClick={()=>setPreset(7)}>7일</button><button onClick={()=>setPreset(30)}>30일</button></div></label><label><span>국가</span><select value={country} onChange={e=>{setCountry(e.target.value);setLeague('전체');setTeam('전체');setPage(1)}}>{countries.map(c=><option key={c}>{c}</option>)}</select></label><label><span>리그</span><select value={league} onChange={e=>{setLeague(e.target.value);setTeam('전체');setPage(1)}}>{visibleLeagues.map(l=><option key={l}>{l}</option>)}</select></label><label><span>팀</span><select value={team} disabled={league==='전체'} onChange={e=>{setTeam(e.target.value);setPage(1)}}><option>전체</option>{(teamsByLeague[league]||[]).map(t=><option key={t}>{t}</option>)}</select></label></div><div className="detailActions"><button onClick={resetDetails}>초기화</button><button className="applyDetail" onClick={applyDetails}>조건 적용</button></div></section>}
 {error&&<div className="apiError"><b>조회 안내</b><span>{error}</span><small>{rangeDays(from,to)>31?'날짜 범위를 줄이면 자동으로 기사를 다시 불러옵니다.':'API 오류가 발생하면 잠시 후 다시 시도해 주세요.'}</small></div>}
 
 <section className="filters"><button className={!tier?'on':''} onClick={()=>selectTier(0)}>전체 신뢰도 <em>{total.toLocaleString()}</em></button>{Object.entries(tierMeta).map(([k,v])=><button key={k} className={tier==k?'on':''} onClick={()=>selectTier(+k)}><i style={{background:v.c}}/>{v.icon} {v.rank} <em>{(tierCounts[k]||0).toLocaleString()}</em></button>)}</section>
 <div className="layout single"><section className="feed"><div className="section-title"><div><span>NEWS ARCHIVE · {dateLabel(detailApplied?from:daysAgo(6))} — {dateLabel(detailApplied?to:today())}</span><h2>{detailApplied&&league!=='전체'?league:detailApplied&&country!=='전체'?country:'전체'} 축구 뉴스</h2></div><small>{total.toLocaleString()}건 중 {filtered.length}건 표시</small></div>{loading&&<div className="loadingCards">기사를 불러오고 있습니다…</div>}{!loading&&filtered.map(a=><article key={a.id} onClick={()=>setSelected(a)}><div className="tierbar" style={{background:a.color}}/><div className="cardtop"><span className={`tier rank-${a.tier}`} style={{color:tierMeta[a.tier].c}}>{tierMeta[a.tier].icon} {tierMeta[a.tier].rank}</span><span className="source">{a.author||a.source}</span>{a.country!=='전체'&&<span className="country">{a.country}</span>}{a.league!=='전체'&&<span className="country leagueBadge">{a.league}</span>}<span className="time"><Clock size={13}/>{a.time}</span></div><h3>{a.ko}</h3><p className="original">{a.title}</p><p className="summary">{a.summary}</p><footer><div>{a.tags.map(t=><span key={t}>#{t}</span>)}</div><button>상세 보기 <ArrowUpRight size={15}/></button></footer></article>)}{!loading&&!filtered.length&&<div className="empty">선택한 조건의 기사가 없습니다.</div>}
 {!loading&&totalPages>1&&<div className="pagination" aria-label="기사 페이지 이동"><button className="pageMove" disabled={page===1} onClick={()=>goToPage(page-1)}><ChevronLeft/> 이전</button><div className="pageNumbers">{pageNumbers[0]>1&&<><button onClick={()=>goToPage(1)}>1</button>{pageNumbers[0]>2&&<span>…</span>}</>}{pageNumbers.map(number=><button key={number} className={page===number?'current':''} aria-current={page===number?'page':undefined} onClick={()=>goToPage(number)}>{number}</button>)}{pageNumbers.at(-1)<maxPage&&<>{pageNumbers.at(-1)<maxPage-1&&<span>…</span>}<button onClick={()=>goToPage(maxPage)}>{maxPage}</button></>}</div><button className="pageMove" disabled={page>=maxPage} onClick={()=>goToPage(page+1)}>다음 <ChevronRight/></button><small>페이지당 10개 · 전체 {total.toLocaleString()}건</small></div>}</section></div></>:view==='ranking'?<section className="rankingPage"><span className="label">SOURCE RANKING</span><h1>소스 랭킹</h1><p>축구 팬 커뮤니티의 최근 신뢰도 평가를 종합한 참고 순위입니다.</p><div className="rankingTabs"><button className={rankTab==='journalists'?'on':''} onClick={()=>setRankTab('journalists')}>축구 기자</button><button className={rankTab==='sites'?'on':''} onClick={()=>setRankTab('sites')}>기사 사이트</button></div><div className="rankingList">{(rankTab==='journalists'?journalistRanking:siteRanking).map(([name,rank],index)=><div key={name}><b>{index+1}</b><span>{name}</span><em className={`rankLabel rankLabel-${Object.values(tierMeta).findIndex(item=>item.rank===rank)+1}`}>{rank}</em></div>)}</div><small className="rankingNote">순위와 등급은 절대적인 사실 판정이 아니며 기자의 담당 구단·국가와 기사 맥락에 따라 달라질 수 있습니다.</small></section>:<section className="videosPage"><span className="label"><PlayCircle size={15}/> FOOTBALL VIDEO</span><h1>축구 영상</h1><p>대표적인 축구 뉴스·리그 공식 유튜브 채널의 영상을 국가별로 모았습니다.</p><div className="videoFilters">{videoCountries.map(item=><button key={item} className={videoCountry===item?'on':''} onClick={()=>setVideoCountry(item)}>{item}</button>)}</div><div className="videoGrid">{footballVideos.filter(video=>videoCountry==='전체'||video.country===videoCountry).map(video=><a className="videoCard" key={video.url} href={video.url} target="_blank" rel="noopener noreferrer"><div className="videoThumb"><img src={video.thumb} alt={video.title} loading="lazy"/><span><PlayCircle/></span><em>{video.country}</em></div><div className="videoInfo"><small>{video.channel} · YouTube</small><h2>{video.title}</h2><p>{video.description}</p><b>유튜브에서 보기 <ExternalLink size={14}/></b></div></a>)}</div><small className="videoNotice">영상은 각 유튜브 채널에서 재생되며 저작권은 해당 채널에 있습니다.</small></section>}</main>
 <footer className="sitefoot"><b>풋볼티어 · FOOTBALL TIER</b><span>축구 뉴스를 더 정확하고, 더 빠르게.</span><small>기사 저작권은 각 언론사에 있으며 검색 결과는 NewsAPI를 통해 제공됩니다.</small></footer>
 {selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className={`modalTier rank-${selected.tier}`} style={{color:tierMeta[selected.tier].c}}>{tierMeta[selected.tier].icon} {tierMeta[selected.tier].rank} · 신뢰도 {selected.confidence}</div><h2>{selected.ko}</h2><p className="modalOriginal">{selected.title}</p><small className="published">{selected.publishedAt&&dateLabel(selected.publishedAt)} · {selected.author?`${selected.author} / `:''}{selected.source}</small><div className="tierBasis">평가 근거 · {selected.tierBasis||'출처 신뢰도 기준'}</div><div className="translation"><Languages/><div><b>한국어 상세 요약</b><p>{selected.summary}</p>{selected.entities?.length>0&&<div className="entities">{selected.entities.map(entity=><span key={entity}>{entity}</span>)}</div>}{selected.translationStatus!=='translated'&&<small>자동 번역을 완료하지 못해 NewsAPI 원문 설명을 표시합니다.</small>}</div></div><div className="bullets"><b>핵심 정보</b><p><CheckCircle2/> {selected.author?`기자 ${selected.author}, 매체 ${selected.source}`:`보도 출처 ${selected.source}`} 기준 {tierMeta[selected.tier].rank} 랭크입니다.</p><p><CheckCircle2/> Gemini가 기사에 명시된 인물·구단·대회와 핵심 사실을 보존해 한국어로 번역·요약합니다.</p><p><CheckCircle2/> 자세한 내용은 원문 기사에서 확인하세요.</p></div><a className="originalBtn" href={selected.url} target="_blank" rel="noopener noreferrer">원문 기사로 이동 <ArrowUpRight/></a></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
