import React,{useCallback,useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,Clock,Globe2,ArrowUpRight,ChevronDown,Radio,Languages,X,CheckCircle2,CalendarDays,ChevronLeft,ChevronRight}from'lucide-react';
import'./styles.css';

const fallbackArticles=[
{id:1,tier:1,source:'OFFICIAL',country:'잉글랜드',league:'프리미어리그',time:'샘플',publishedAt:new Date().toISOString(),title:'Manchester City complete signing of teenage midfielder',ko:'맨체스터 시티, 유망주 미드필더 영입 공식 발표',summary:'구단은 장기 계약 체결을 공식 확인했다.',tags:['이적','공식'],confidence:99,color:'#65d89a',url:'https://www.mancity.com/news'},
{id:2,tier:2,source:'The Athletic',country:'잉글랜드',league:'프리미어리그',time:'샘플',publishedAt:new Date().toISOString(),title:'Arsenal make contact over deal for versatile defender',ko:'아스널, 멀티 수비수 영입 위해 첫 접촉',summary:'아스널이 선수 측과 초기 대화를 시작했다.',tags:['프리미어리그','이적'],confidence:92,color:'#69d9e8',url:'https://www.nytimes.com/athletic/football/'},
{id:3,tier:2,source:'Fabrizio Romano',country:'이탈리아',league:'세리에 A',time:'샘플',publishedAt:new Date().toISOString(),title:'Agreement reached, final documents being prepared',ko:'협상 합의 도달…최종 서류 준비 중',summary:'구단과 선수 모두 계약 조건에 동의했다.',tags:['Here we go','속보'],confidence:90,color:'#69d9e8',url:'https://x.com/FabrizioRomano'}
];
const tierMeta={1:{rank:'공식·최상',icon:'◆',name:'최고 신뢰',c:'#f3c969'},2:{rank:'신뢰',icon:'◇',name:'높은 신뢰',c:'#69d9e8'},3:{rank:'참고',icon:'⬟',name:'추가 확인',c:'#f0b93f'},4:{rank:'주의',icon:'⬢',name:'낮은 신뢰',c:'#b97850'}};
const journalistRanking=[['David Ornstein','공식·최상'],['Paul Joyce','공식·최상'],['Simon Stone','공식·최상'],['James Pearce','공식·최상'],['Romeo Agresti','공식·최상'],['Fabrizio Romano','신뢰'],['Matteo Moretto','신뢰'],['Fabrice Hawkins','신뢰'],['Gianluca Di Marzio','신뢰'],['Florian Plettenberg','신뢰'],['Gerard Romero','신뢰'],['Ben Jacobs','신뢰'],['Tancredi Palmeri','주의']];
const siteRanking=[['구단 공식 채널','공식·최상'],['BBC Sport','신뢰'],['The Athletic','신뢰'],['The Times','신뢰'],['Sky Sports','신뢰'],['The Guardian','신뢰'],['The Telegraph','신뢰'],['Marca / L’Équipe','참고'],['ESPN / Goal','참고'],['90min / CaughtOffside','참고'],['The Sun / Tuttosport','주의']];
const countries=['전체','잉글랜드','스페인','이탈리아','프랑스'];
const leagues=['전체','프리미어리그','라리가','세리에 A','리그 1'];
const leaguesByCountry={잉글랜드:['프리미어리그'],스페인:['라리가'],이탈리아:['세리에 A'],프랑스:['리그 1']};
const transferWindows={잉글랜드:[[1,1,2,3],[6,1,9,1]],스페인:[[1,2,2,3],[7,1,9,1]],이탈리아:[[1,2,2,3],[7,1,9,1]],프랑스:[[1,1,2,3],[6,10,9,1]]};
const inWindow=(name,now=new Date())=>(transferWindows[name]||[]).some(([sm,sd,em,ed])=>{const y=now.getFullYear(),start=new Date(y,sm-1,sd),end=new Date(y,em-1,ed,23,59,59);return now>=start&&now<=end});
const scheduleFor=(selectedCountry,now=new Date())=>{const active=selectedCountry==='전체'?countries.slice(1).filter(c=>inWindow(c,now)):inWindow(selectedCountry,now)?[selectedCountry]:[];return{active,interval:active.length?5*60*1000:60*60*1000}};
const isoDate=d=>d.toISOString().slice(0,10);
const today=()=>isoDate(new Date());
const yearsAgo=n=>{const d=new Date();d.setFullYear(d.getFullYear()-n);return isoDate(d)};
const dateLabel=value=>new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'short',day:'numeric'}).format(new Date(value));

function App(){
 const[tier,setTier]=useState(0),[country,setCountry]=useState('전체'),[league,setLeague]=useState('전체'),[query,setQuery]=useState(''),[appliedQuery,setAppliedQuery]=useState(''),[selected,setSelected]=useState(null),[lang,setLang]=useState('KO'),[view,setView]=useState('news'),[rankTab,setRankTab]=useState('journalists');
 const[from,setFrom]=useState(yearsAgo(3)),[to,setTo]=useState(today()),[page,setPage]=useState(1),[pageSize]=useState(10),[articles,setArticles]=useState([]),[total,setTotal]=useState(0),[lastUpdated,setLastUpdated]=useState(new Date()),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const visibleLeagues=country==='전체'?leagues:['전체',...(leaguesByCountry[country]||[])];
 const loadArticles=useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams({from,to,page:String(page),pageSize:String(pageSize),country,league});if(appliedQuery)p.set('q',appliedQuery);const response=await fetch(`/api/articles?${p}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'기사 조회에 실패했습니다.');setArticles(data.articles||[]);setTotal(data.totalResults||0);setLastUpdated(new Date())}catch(e){setError(e.message);setArticles(fallbackArticles);setTotal(fallbackArticles.length)}finally{setLoading(false)}},[from,to,page,pageSize,country,league,appliedQuery]);
 useEffect(()=>{loadArticles()},[loadArticles]);
 useEffect(()=>{const{interval}=scheduleFor(country);const timer=setInterval(loadArticles,interval);return()=>clearInterval(timer)},[country,loadArticles]);
 const schedule=scheduleFor(country);
 const filtered=useMemo(()=>articles.filter(a=>!tier||a.tier===tier),[articles,tier]);
 const totalPages=Math.max(1,Math.ceil(total/pageSize));
 const maxPage=Math.min(totalPages,100);
 const pageNumbers=useMemo(()=>{const start=Math.max(1,Math.min(page-2,maxPage-4)),end=Math.min(maxPage,start+4);return Array.from({length:end-start+1},(_,i)=>start+i)},[page,maxPage]);
 const goToPage=next=>{setPage(next);requestAnimationFrame(()=>document.querySelector('.feed')?.scrollIntoView({behavior:'smooth',block:'start'}))};
 const applySearch=e=>{e.preventDefault();setPage(1);setAppliedQuery(query.trim())};
 const setPreset=days=>{const end=new Date(),start=new Date();if(days===1095)start.setFullYear(start.getFullYear()-3);else start.setDate(start.getDate()-days);setFrom(isoDate(start));setTo(isoDate(end));setPage(1)};
 return <div className="app"><header><div className="brand"><div className="logo"><img src="/football-tier-logo-transparent.png" alt="풋볼티어 로고"/></div><b>풋볼 <i>티어</i></b></div><nav><button className={view==='news'?'active':''} onClick={()=>setView('news')}>뉴스 피드</button><button className={view==='ranking'?'active':''} onClick={()=>setView('ranking')}>소스 랭킹</button></nav><button className="lang" onClick={()=>setLang(lang==='KO'?'EN':'KO')}><Globe2 size={16}/>{lang}<ChevronDown size={14}/></button></header>
 <main>{view==='news'?<><section className="hero"><div className="eyebrow"><Radio size={14}/> 3-YEAR NEWS ARCHIVE</div><h1>최근 3년의 축구 뉴스,<br/><span>한 번에 찾아보세요.</span></h1><p>NewsAPI에서 실제 해외 축구 기사를 불러와<br/>날짜·국가·리그·신뢰도별로 탐색합니다.</p><div className="stats"><div><strong>{total.toLocaleString()}</strong><small>검색된 기사</small></div><div><strong>3Y</strong><small>최대 조회 기간</small></div><div><strong>{page}</strong><small>현재 페이지</small></div></div></section>
 <section className="toolbar"><form className="search" onSubmit={applySearch}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="팀, 선수, 리그 또는 매체 검색"/><button type="submit">검색</button></form><div className="updatePanel"><div className="update"><span className={loading?'refreshing':''}/>{loading?'기사 불러오는 중':`마지막 업데이트 ${lastUpdated.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`}</div><button onClick={loadArticles} disabled={loading}>지금 새로고침</button><small>{schedule.active.length?`이적시장 모드 · 5분 간격 (${schedule.active.join(' · ')})`:'일반 모드 · 1시간 간격'}</small></div></section>
 <section className="archivePanel"><div className="archiveTitle"><CalendarDays size={18}/><div><b>기사 날짜 범위</b><small>NewsAPI 요금제의 실제 아카이브 한도 내에서 최대 최근 3년</small></div></div><div className="dateInputs"><label>시작일<input type="date" min={yearsAgo(3)} max={to} value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><span>—</span><label>종료일<input type="date" min={from} max={today()} value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label></div><div className="datePresets"><button onClick={()=>setPreset(7)}>최근 7일</button><button onClick={()=>setPreset(30)}>최근 30일</button><button onClick={()=>setPreset(365)}>최근 1년</button><button onClick={()=>setPreset(1095)}>최근 3년</button></div></section>
 {error&&<div className="apiError"><b>NewsAPI 안내</b><span>{error}</span><small>현재는 샘플 기사를 표시합니다. Vercel 환경변수와 NewsAPI 플랜의 날짜 범위를 확인하세요.</small></div>}
 <section className="categoryFilters"><div className="filterGroup"><b>국가별</b>{countries.map(c=><button key={c} className={country===c?'on':''} onClick={()=>{setCountry(c);setLeague('전체');setPage(1)}}>{c}</button>)}</div><div className="filterGroup"><b>리그별</b>{visibleLeagues.map(l=><button key={l} className={league===l?'on':''} onClick={()=>{setLeague(l);setPage(1)}}>{l}</button>)}</div></section>
 <section className="filters"><button className={!tier?'on':''} onClick={()=>setTier(0)}>전체 신뢰도 <em>{articles.length}</em></button>{Object.entries(tierMeta).map(([k,v])=><button key={k} className={tier==k?'on':''} onClick={()=>setTier(+k)}><i style={{background:v.c}}/>{v.icon} {v.rank} <em>{articles.filter(a=>a.tier==k).length}</em></button>)}</section>
 <div className="layout single"><section className="feed"><div className="section-title"><div><span>NEWS ARCHIVE · {dateLabel(from)} — {dateLabel(to)}</span><h2>{league!=='전체'?league:country!=='전체'?country:'해외'} 축구 뉴스</h2></div><small>{total.toLocaleString()}건 중 {filtered.length}건 표시</small></div>{loading&&<div className="loadingCards">기사를 불러오고 있습니다…</div>}{!loading&&filtered.map(a=><article key={a.id} onClick={()=>setSelected(a)}><div className="tierbar" style={{background:a.color}}/><div className="cardtop"><span className={`tier rank-${a.tier}`} style={{color:tierMeta[a.tier].c}}>{tierMeta[a.tier].icon} {tierMeta[a.tier].rank}</span><span className="source">{a.author||a.source}</span>{a.country!=='전체'&&<span className="country">{a.country}</span>}{a.league!=='전체'&&<span className="country leagueBadge">{a.league}</span>}<span className="time"><Clock size={13}/>{a.time}</span></div><h3>{a.ko}</h3><p className="original">{a.title}</p><p className="summary">{a.summary}</p><footer><div>{a.tags.map(t=><span key={t}>#{t}</span>)}</div><button>상세 보기 <ArrowUpRight size={15}/></button></footer></article>)}{!loading&&!filtered.length&&<div className="empty">선택한 조건의 기사가 없습니다.</div>}
 {!loading&&totalPages>1&&<div className="pagination" aria-label="기사 페이지 이동"><button className="pageMove" disabled={page===1} onClick={()=>goToPage(page-1)}><ChevronLeft/> 이전</button><div className="pageNumbers">{pageNumbers[0]>1&&<><button onClick={()=>goToPage(1)}>1</button>{pageNumbers[0]>2&&<span>…</span>}</>}{pageNumbers.map(number=><button key={number} className={page===number?'current':''} aria-current={page===number?'page':undefined} onClick={()=>goToPage(number)}>{number}</button>)}{pageNumbers.at(-1)<maxPage&&<>{pageNumbers.at(-1)<maxPage-1&&<span>…</span>}<button onClick={()=>goToPage(maxPage)}>{maxPage}</button></>}</div><button className="pageMove" disabled={page>=maxPage} onClick={()=>goToPage(page+1)}>다음 <ChevronRight/></button><small>페이지당 10개 · 전체 {total.toLocaleString()}건</small></div>}</section></div></>:<section className="rankingPage"><span className="label">SOURCE RANKING</span><h1>소스 랭킹</h1><p>축구 팬 커뮤니티의 최근 신뢰도 평가를 종합한 참고 순위입니다.</p><div className="rankingTabs"><button className={rankTab==='journalists'?'on':''} onClick={()=>setRankTab('journalists')}>축구 기자</button><button className={rankTab==='sites'?'on':''} onClick={()=>setRankTab('sites')}>기사 사이트</button></div><div className="rankingList">{(rankTab==='journalists'?journalistRanking:siteRanking).map(([name,rank],index)=><div key={name}><b>{index+1}</b><span>{name}</span><em className={`rankLabel rankLabel-${Object.values(tierMeta).findIndex(item=>item.rank===rank)+1}`}>{rank}</em></div>)}</div><small className="rankingNote">순위와 등급은 절대적인 사실 판정이 아니며 기자의 담당 구단·국가와 기사 맥락에 따라 달라질 수 있습니다.</small></section>}</main>
 <footer className="sitefoot"><b>풋볼티어 · FOOTBALL TIER</b><span>축구 뉴스를 더 정확하고, 더 빠르게.</span><small>기사 저작권은 각 언론사에 있으며 검색 결과는 NewsAPI를 통해 제공됩니다.</small></footer>
 {selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className={`modalTier rank-${selected.tier}`} style={{color:tierMeta[selected.tier].c}}>{tierMeta[selected.tier].icon} {tierMeta[selected.tier].rank} · 신뢰도 {selected.confidence}</div><h2>{selected.ko}</h2><p className="modalOriginal">{selected.title}</p><small className="published">{selected.publishedAt&&dateLabel(selected.publishedAt)} · {selected.author?`${selected.author} / `:''}{selected.source}</small><div className="tierBasis">평가 근거 · {selected.tierBasis||'출처 신뢰도 기준'}</div><div className="translation"><Languages/><div><b>한국어 상세 요약</b><p>{selected.summary}</p>{selected.entities?.length>0&&<div className="entities">{selected.entities.map(entity=><span key={entity}>{entity}</span>)}</div>}{selected.translationStatus!=='translated'&&<small>자동 번역을 완료하지 못해 NewsAPI 원문 설명을 표시합니다.</small>}</div></div><div className="bullets"><b>핵심 정보</b><p><CheckCircle2/> {selected.author?`기자 ${selected.author}, 매체 ${selected.source}`:`보도 출처 ${selected.source}`} 기준 {tierMeta[selected.tier].rank} 랭크입니다.</p><p><CheckCircle2/> Gemini가 기사에 명시된 인물·구단·대회와 핵심 사실을 보존해 한국어로 번역·요약합니다.</p><p><CheckCircle2/> 자세한 내용은 원문 기사에서 확인하세요.</p></div><a className="originalBtn" href={selected.url} target="_blank" rel="noopener noreferrer">원문 기사로 이동 <ArrowUpRight/></a></div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
